num_steps: 100000
batch_size: 32
lr: 0.005
memory_size: 300000
gamma: 0.95
multi_step: 1
target_entropy_ratio: 0.98
start_steps: 2000
update_interval: 1
target_update_interval: 32
use_per: False
dueling_net: False
num_eval_steps: 100
max_episode_steps: 400
log_interval: 10
eval_interval: 10000
